import 'package:freezed_annotation/freezed_annotation.dart';

part 'financial_trend_dto.freezed.dart';

/// Domain Entity: Financial Trend Data Transfer Object
///
/// Purpose: Central data structure containing all financial trend information
/// - Net balance progression over time
/// - Income vs expense comparisons
/// - Health metrics and insights
/// - Single source of truth for financial dashboard
@freezed
class FinancialTrendDTO with _$FinancialTrendDTO {
  const factory FinancialTrendDTO({
    /// Monthly balance points showing cumulative net worth trend
    required List<MonthlyBalancePoint> netBalanceTrend,
    
    /// Monthly income vs expense comparisons for bar chart
    required List<IncomeExpenseComparison> monthlyComparisons,
    
    /// Key financial health metrics
    required FinancialHealthMetrics healthMetrics,
    
    /// Intelligent insights about financial patterns
    required List<FinancialInsight> insights,
  }) = _FinancialTrendDTO;
}

/// Data class representing a single month's balance data point
@freezed
class MonthlyBalancePoint with _$MonthlyBalancePoint {
  const factory MonthlyBalancePoint({
    /// Month identifier in YYYY-MM format
    required String monthKey,
    
    /// First day of the month for chart positioning
    required DateTime date,
    
    /// Cumulative net balance at end of month
    required double cumulativeBalance,
    
    /// Total income for this month
    required double monthlyIncome,
    
    /// Total expenses for this month
    required double monthlyExpense,
    
    /// Net change for this month (income - expense)
    required double netChange,
  }) = _MonthlyBalancePoint;
}

/// Data class for comparing income vs expense in a given month
@freezed
class IncomeExpenseComparison with _$IncomeExpenseComparison {
  const factory IncomeExpenseComparison({
    /// Month identifier in YYYY-MM format
    required String monthKey,
    
    /// Total income for the month
    required double income,
    
    /// Total expenses for the month
    required double expense,
    
    /// Difference (income - expense)
    required double difference,
  }) = _IncomeExpenseComparison;
}

/// Data class containing key financial health indicators
@freezed
class FinancialHealthMetrics with _$FinancialHealthMetrics {
  const factory FinancialHealthMetrics({
    /// Average monthly income over analyzed period
    required double averageMonthlyIncome,
    
    /// Average monthly expenses over analyzed period
    required double averageMonthlyExpense,
    
    /// Savings rate as percentage (income - expenses) / income * 100
    required double savingsRate,
    
    /// Income consistency score (0-100, higher = more consistent)
    required double incomeConsistency,
    
    /// Best performing month details
    required MonthlyPerformance bestMonth,
    
    /// Worst performing month details
    required MonthlyPerformance worstMonth,
  }) = _FinancialHealthMetrics;
}

/// Data class representing performance metrics for a specific month
@freezed
class MonthlyPerformance with _$MonthlyPerformance {
  const factory MonthlyPerformance({
    /// Month identifier in YYYY-MM format
    required String monthKey,
    
    /// Net balance at end of month
    required double netBalance,
    
    /// Savings rate for the month
    required double savingsRate,
  }) = _MonthlyPerformance;
}

/// Enum for categorizing insight types
enum InsightType {
  trend,      // General trend analysis
  anomaly,    // Unusual spending patterns
  milestone,  // Financial milestones reached
  warning,    // Potential financial issues
  suggestion, // Recommendations for improvement
}

/// Enum for insight severity levels
enum InsightSeverity {
  info,     // Informational
  warning,  // Requires attention
  critical, // Immediate action needed
}

/// Data class for financial insights generated by intelligence algorithms
@freezed
class FinancialInsight with _$FinancialInsight {
  const factory FinancialInsight({
    /// Unique identifier for the insight
    required String id,
    
    /// Type of insight for categorization
    required InsightType type,
    
    /// Severity level indicating importance
    required InsightSeverity severity,
    
    /// Short descriptive title
    required String title,
    
    /// Detailed explanation message
    required String message,
    
    /// When the insight was created
    required DateTime createdDate,
    
    /// Whether the user has acknowledged/read this insight
    required bool isRead,
    
    /// Optional metadata for additional context
    Map<String, dynamic>? metadata,
  }) = _FinancialInsight;
}